# Generated by Django 5.2 on 2025-05-02 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kiosko', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria2',
        ),
    ]
